### ISSUE TITLE
property:proParteSynonym

### ISSUE THREAD

**Issue by nielsklazenga** [tdwg/tcs2#200]
### proParteSynonym (property)

|    |    |
|----|----|
| Label | Pro Parte Synonym |
| Definition | Taxon Concept of which the name is a synonym of the name of the subject Taxon Concept, but with a broader circumscription than the subject Taxon Concept |
| Usage notes |  |
| Comments |  |
| Required | No |
| Repeatable | Yes |
| Constraints | Object |

**Comment by nielsklazenga** [comment]
This term, despite being a new term, has been included, because we consider that it was included in the `has synonym` relationship type in TCS 1. Since we are proposing to break down the Taxon Relationship class, which only leaves Taxon Alignments in a separate class (#43), `pro parte synonym` is best dealt with as a property of `Taxon Concept`. Pro parte synonyms are best dealt with as a Taxon Alignment, but the mapping is not straightforward and the rationale for including this extra term is to be able to exchange this information without the need for an expert opinion.

The definition according to Franz and Peet (2009):

> **[is a partial synonym for: ]** name 1 is a synonym of name 2 including part of name 2’s entire
taxonomic range

..., which I based the definition above on indicates that the name of a `pro parte synonym` is a `synonym`, meaning that the translation of the use of 'p.p.' in a publication to `proParteSynonym` is not more straightforward than to a taxon alignment type. We need to consider whether the mapping from `pro parte synonym` to `is included in` (or `is proper subpart of` as we propose) is as straightforward as the TCS 1 User Guide suggests, but also, more importantly, how likely inexpert users are to misinterpret the use of 'p.p.' for a `pro parte synonym`, as that would oviate the use case for this property.

**Comment by Archilegt** [comment]
Not always because of "broader circumscription" but also because of misidentifications/misapplications, often without implying a different taxonomic concept but just careless examination of specimens. The term is difficult to define because it overlaps with taxonomic concepts and scientific names.

Definition: Taxonomic Concept including more than one currently recognized taxonomic concept, while only one of those taxonomic concepts is being considered a synonym of the `acceptedNameUsage`.

**Comment by nielsklazenga** [comment]
I have a suggestion to make. I think TCS really should not allow (or endorse) the exchange of "pro-parte synonyms" and "misapplications" (#199), whatever they are, in this form.

These things are really taxon relationships/alignments (*cf.* #43), not nomenclatural relationships like the labels suggest, and should be exchanged as such. The rational for having these terms in the first place is that people want to exchange the information straight from the page without data entry folk having to do expert interpretations (which would make the assertion theirs and not by the authors of the publication). So lets make that possible under Taxon Alignments (which is what we call Taxon Relationships now), so the data ends up in the place it belongs.

We have added a controlled term `intersects` (#57) to the controlled vocabulary for the `relationshipType` property (#44). This relationship type can be applied to "misapplications" and "pro-parte synonyms", as well as everything else you may find in a "full synonomy", including "synonyms" if you are talking about more than the nomenclatural type. We can add a new property, in addition to `relationshipType` (which we could rename) to indicate what sort of assertion the alignment is based on. For me, just a `skos:note` saying that it comes from a synonymy or nomenclature session would do it, but others might prefer something more granular.

**Comment by nielsklazenga** [comment]
Opened issue #205 to replace this and #199.
