### ISSUE TITLE
"sec." in Example 6 (Avibase) not a publication

### ISSUE THREAD

**Issue by camwebb** [tdwg/tcs2#219]
Small point, but seems worth addressing since the examples will be read as normative. The "sec" in the preferred names in [example 6](https://github.com/tdwg/tcs2/blob/examples/docs/examples/example6/example6.ttl) is a TC, not a publication, as is the usual usage. Is there a version of Avibase that can be used as the publication part of the "sec"?

**Comment by nielsklazenga** [comment]
Avibase IDs are unique for a certain taxon definition, so no versioning is necessary and I expect Avibase will not have it. I agree we need to find a better way to do this though. Since the only thing we need to achieve is make the taxon concept label unique, maybe we can just add the Avibase ID to the name part of the label (i.e. before the 'sec.'), so we can just have Avibase as the `accordingTo`?

```turtle
<https://avibase.ca/82745BAA> a :TaxonConcept ;
    dcterms:identifier "avibase-82745BAA" ;
    dcterms:title "Circus [cyaneus or hudsonius] #82745BAA sec. Avibase" ;
    :taxonName [ a :TaxonName ;
            :taxonNameString "Circus [cyaneus or hudsonius]" ] ;
    :accordingTo <https://avibase.bsc-eoc.org> .

```

**Comment by nielsklazenga** [comment]
Maybe this is unrelated, but we should have a think about IDs for concepts from websites as well. Catalogue of Life has a new version every month, but I think the URIs stay the same if a definition has changed, but the name has not. Should we append the version to the ID? (I think we should)

Same with ITIS, where the URI stays the same if the name stays the same, but at any time the thing the ID represents is a taxon, not a name. ITIS does not have versions, I think, but it might be good to append a hash with the date to the URI for the ID?

None of this has to be normative, but I think it will be good to highlight these issues and I think the examples should show people what we consider best practice.

**Comment by nielsklazenga** [comment]
https://github.com/tdwg/tcs2/pull/218/commits/a141fd62163c471ffddced886b0daf0cc1b8047b

**Comment by nielsklazenga** [comment]
@camwebb , I think it might be better to use `dcterms:identifier` rather than `dcterms:title` for Avibase (and similar) concepts:

```turtle
@prefix tcs: <http://rs.tdwg.org/tcs/terms/> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix skosxl: <http://www.w3.org/2008/05/skos-xl#> .

<https://avibase.ca/82745BAA> a tcs:TaxonConcept ;
    dcterms:identifier "avibase-82745BAA" ;
    tcs:accordingTo <https://avibase.bsc-eoc.org> ;
    tcs:acceptedName [ a skosxl:Label ;
            skosxl:literalForm "Circus [cyaneus or hudsonius]" ] ;
    tcs:isCongruentWith <https://eg.tdwg.org/tcs/tc/1> .
```
