### ISSUE TITLE
Making TG agendas and minutes discoverable

### ISSUE THREAD

**Issue by jar398** [tdwg/tcs2#220]
There is a `meetings/` directory in the repository which has information on only one meeting.  But there have been other meetings. The agendas seem to reside inside of github issues.  May I suggest putting a `README.md` in the `meetings` directory, and/or an explanation in the main `README.md`, guiding visitors on how to find meeting agendas and minutes? Links would be great, but even a generic comment saying to search for meetings in the issues list would be useful.

I could not find any minutes other those for Dec 10 2021. If they exist maybe they could be made discoverable in a similar way. Or, if there are none, maybe say so somewhere.

**Comment by nielsklazenga** [comment]
Thanks @jar398 , will do that.

**Comment by nielsklazenga** [comment]
https://github.com/tdwg/tcs2/commit/74584686093636b77d2787dc81d18d47e41fe23e
