### ISSUE TITLE
Task Group Meeting: 14 December 2022, 20:00–21:30 UTC

### ISSUE THREAD

**Issue by nielsklazenga** [tdwg/tcs2#221]
Report from the meeting held 14 December 2022:

[TCS 2 Task Group Meeting 2022-12-14.pdf](https://github.com/tdwg/tcs2/files/10234785/TCS.2.Task.Group.Meeting.2022-12-14.pdf)

**Comment by jliljeblad** [comment]
Sorry I couldn't make it to the meeting. Realized too late the Christmas dinner with work would make me get home late and too tired.
