### ISSUE TITLE
property:combinationExAuthorship

### ISSUE THREAD

**Issue by nielsklazenga** [tdwg/tcs2#27]
### combinationExAuthorship (property)

|    |    |
|----|----|
| Label | Combination Ex Authorship |
| Definition | People the combination has been attributed to, but who didn’t validly publish it. |
| Usage notes |  |
| Comments |  |
| Required | No |
| Repeatable | No |
| Constraints | Literal |

**Comment by nielsklazenga** [comment]
We could do this:

- `basionymAuthorship`
- `newCombinationAuthorship`
- `basionymAscribedAuthorship`
- `newCombinationAscribedAuthorship`

This _resolves_ the problems that at least I had with the parsed authorships: it being semantically empty and incorrect use of existing terms. `newCombinationAuthorship` rather than `combinationAuthorship`, because a 'combination' is a genus name with one or two epithets, so basionyms can also be combinations and new combinations are not necessarily combinations. The latter is not actually true as we would not call a uninomial '_comb. nov._' but `_stat. nov._`. `newCombinationOrStatusAuthorship` might get a bit too pedantic though (but I like it).

**Comment by mdoering** [comment]
my thinking and how its implemented in GBIF, COL and ChecklistBank is that basionymAuthorship only exists when you have a subsequent combination and as such brackets around the authorship. The authorship of the original name is placed in the combinationAuthorship - the authorship for the exact combination you are looking at. In zoology always empty in case of "new" combinations.

Btw, in [ColDP](https://github.com/CatalogueOfLife/coldp?tab=readme-ov-file#name) we have also started to allow list of author/agent instances to be listed as the authorship, not just strings.

**Comment by nielsklazenga** [comment]
@mdoering your comment crossed with the edit I just made to my comment. We are in agreement. I will get over the fact that `combinationAuthorship` is not quite correct (in my mind at least). The suggestion to use 'Ascribed' rather than 'Ex' stands.

I was going to mention the Author Agents as well. IPNI and Tropicos have had them for years. So, we should have it. I am assuming we do not want roles here?

**Comment by mdoering** [comment]
> So, just `author` for the Agent authors? I thought we might just put it in, even though it is not strictly in TCS 1.

yes! Just not sure from the top of my head how an ordered list needs to be expressed...

**Comment by nielsklazenga** [comment]
There is actually two ways we can do it.

Either:

- `basionymAuthorship`
- `combinationAuthorship`
- `basionymAscribedAuthorship`
- `combinationAscribedAuthorship`
- `author` (for the Agent authors)

Or:

- `basionymAuthor`
- `combinationAuthor`
- `basionymAscribedAuthor`
- `combinationAscribedAuthor`
- `basionymAuthorLiteral`
- `combinationAuthorLiteral`
- `basionymAscribedAuthorLiteral`
- `combinationAscribedAuthorLiteral`

I think I prefer the second option, which is also closest to what IPNI and Tropicos are already doing.

**Comment by nielsklazenga** [comment]
Merging with #239.
